### ISSUE TITLE
Scorm don't show correctly

### ISSUE THREAD

**Issue by mpldev** [sakaicontrib/SCORM.2004.3ED.RTE#20]
Have a good day.

Sakai shows behind scorm viewer.

![scorm-window](https://cloud.githubusercontent.com/assets/20426825/18590072/0e7ff156-7bf3-11e6-92c0-3be9181d8c0d.PNG)

**Comment by bjones86** [comment]
@mpldev, we currently don't use GitHub issues. All task management is done through the Sakai Project JIRA: https://jira.sakaiproject.org/projects/SCO/

It is advised that you search the JIRA for existing issues before filing a ticket. This issue has already been identified: https://jira.sakaiproject.org/browse/SCO-114

Thanks.
